[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hot-seahorse"
version = "0.1.0"

[tool.setuptools]
packages = ["src"]

[tool.pytest.ini_options]
pythonpath = [".", "src"]